Repository phytec/partup, pull requests merged in 2023-07, with the labels that each got.

#55 tests: utils: Add unit test for pu_str_pre_remove
  tests/utils.c
Labels: tests

#34 Test partup with loop device in github action
  .github/workflows/system-tests.yml
  README.rst
  tests/config/system-tests/gpt.yaml
  tests/config/system-tests/msdos.yaml
Labels: CI, tests

#58 Fix debug output
  src/pu-log.c
Labels: bug

#59 tests: command: Do not use g_assert_cmpstrv()
  tests/command.c
Labels: bug

#60 README: switch documentation badge to readthedocs.io
  README.rst
Labels: documentation
